### ISSUE TITLE
moudle.js报错

### ISSUE THREAD

**Issue by ch4rc0al1080** [AntSwordProject/ant#2]
已经配好`mongodb`，启动`node app`时报错

```bash
module.js:478
    throw err;
    ^

Error: Cannot find module 'mongodb/node_modules/bson'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/ant-master/web/node_modules/mongoose/lib/drivers/node-mongodb-native/objectid.js:8:52)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

**Comment by Medicean** [comment]
node与mongodb 的版本需要和 README 中保持一致，然后再重新运行 

```
npm --registry=https://registry.npm.taobao.org install
```
